language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

# command to install dependencies
install:
 - pip install .
 - pip install nose
 - pip install python-coveralls

# command to run tests
script: nosetests --with-coverage

after_success:
- coveralls
